from __future__ import annotations

import io
import os
import zipfile
from typing import Dict


def create_project_zip(files: Dict[str, str], design_name: str = "uvm_project") -> io.BytesIO:
    """Create an in-memory ZIP of generated SV files ready for download.

    Args:
        files: {filename: content} dict (from pipeline generated_files).
        design_name: top-level directory name inside the ZIP.

    Returns:
        BytesIO stream with the ZIP data.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Write a brief README
        readme = f"""UVM Testbench — {design_name}
Generated by Semiconductor UVM Pipeline
============================================

Files:
"""
        for fname in sorted(files.keys()):
            readme += f"  - {fname}\n"
        zf.writestr(f"{design_name}/README.txt", readme)

        # Write a compile.f filelist
        sv_files = [fname for fname in sorted(files.keys()) if fname.endswith(".sv")]
        filelist = "\n".join(f"${{UVM_HOME}}/src/uvm.sv" if fname == "compile.f" else fname for fname in sv_files) + "\n"
        zf.writestr(f"{design_name}/compile.f", filelist)

        # Write each generated file
        for fname, content in files.items():
            arcname = f"{design_name}/{fname}"
            zf.writestr(arcname, content)

    buf.seek(0)
    return buf
